# Generated by Django 4.1.1 on 2023-05-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calories_goal',
            field=models.FloatField(default=2500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='carbohydrates_goal',
            field=models.FloatField(default=140),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fats_goal',
            field=models.FloatField(default=76),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='protein_goal',
            field=models.FloatField(default=343),
        ),
    ]
