# Generated by Django 4.1.1 on 2023-05-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_exercise_date_alter_food_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='request_counter',
        ),
        migrations.AddField(
            model_name='dailyintake',
            name='request_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conversation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
